services:
  - type: web
    name: driver-drowsiness-demo
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app --bind 0.0.0.0:$PORT
